// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ranking.proto

package ranking

import (
	"context"

	"freeexchanged/app/ranking/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetTopReq  = pb.GetTopReq
	GetTopResp = pb.GetTopResp
	RankItem   = pb.RankItem

	Ranking interface {
		GetTop(ctx context.Context, in *GetTopReq, opts ...grpc.CallOption) (*GetTopResp, error)
	}

	defaultRanking struct {
		cli zrpc.Client
	}
)

func NewRanking(cli zrpc.Client) Ranking {
	return &defaultRanking{
		cli: cli,
	}
}

func (m *defaultRanking) GetTop(ctx context.Context, in *GetTopReq, opts ...grpc.CallOption) (*GetTopResp, error) {
	client := pb.NewRankingClient(m.cli.Conn())
	return client.GetTop(ctx, in, opts...)
}
