// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package articleClient

import (
	"context"

	"freeexchanged/app/article/cmd/rpc/article"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleInfo      = article.ArticleInfo
	GetArticleReq    = article.GetArticleReq
	GetArticleResp   = article.GetArticleResp
	ListArticlesReq  = article.ListArticlesReq
	ListArticlesResp = article.ListArticlesResp
	PublishReq       = article.PublishReq
	PublishResp      = article.PublishResp

	Article interface {
		Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
		GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error)
		ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	client := article.NewArticleClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultArticle) GetArticle(ctx context.Context, in *GetArticleReq, opts ...grpc.CallOption) (*GetArticleResp, error) {
	client := article.NewArticleClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticle) ListArticles(ctx context.Context, in *ListArticlesReq, opts ...grpc.CallOption) (*ListArticlesResp, error) {
	client := article.NewArticleClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}
