// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package server

import (
	"context"

	"freeexchanged/app/favorite/cmd/rpc/favorite"
	"freeexchanged/app/favorite/cmd/rpc/internal/logic"
	"freeexchanged/app/favorite/cmd/rpc/internal/svc"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	favorite.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServer) Ping(ctx context.Context, in *favorite.PingReq) (*favorite.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
