// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/rate.proto

package rate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 获取汇率 ---
type GetRateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // 源货币，如 "USD"
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // 目标货币，如 "CNY"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateReq) Reset() {
	*x = GetRateReq{}
	mi := &file_desc_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateReq) ProtoMessage() {}

func (x *GetRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateReq.ProtoReflect.Descriptor instead.
func (*GetRateReq) Descriptor() ([]byte, []int) {
	return file_desc_rate_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetRateReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetRateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`                           // 汇率值，如 7.2534
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 最后更新时间戳 (Unix)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateResp) Reset() {
	*x = GetRateResp{}
	mi := &file_desc_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResp) ProtoMessage() {}

func (x *GetRateResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResp.ProtoReflect.Descriptor instead.
func (*GetRateResp) Descriptor() ([]byte, []int) {
	return file_desc_rate_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateResp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetRateResp) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetRateResp) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetRateResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// --- 获取支持的货币列表 ---
type GetSupportedCurrenciesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedCurrenciesReq) Reset() {
	*x = GetSupportedCurrenciesReq{}
	mi := &file_desc_rate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedCurrenciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedCurrenciesReq) ProtoMessage() {}

func (x *GetSupportedCurrenciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_rate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedCurrenciesReq.ProtoReflect.Descriptor instead.
func (*GetSupportedCurrenciesReq) Descriptor() ([]byte, []int) {
	return file_desc_rate_proto_rawDescGZIP(), []int{2}
}

type GetSupportedCurrenciesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []string               `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedCurrenciesResp) Reset() {
	*x = GetSupportedCurrenciesResp{}
	mi := &file_desc_rate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedCurrenciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedCurrenciesResp) ProtoMessage() {}

func (x *GetSupportedCurrenciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_rate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedCurrenciesResp.ProtoReflect.Descriptor instead.
func (*GetSupportedCurrenciesResp) Descriptor() ([]byte, []int) {
	return file_desc_rate_proto_rawDescGZIP(), []int{3}
}

func (x *GetSupportedCurrenciesResp) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_desc_rate_proto protoreflect.FileDescriptor

const file_desc_rate_proto_rawDesc = "" +
	"\n" +
	"\x0fdesc/rate.proto\x12\x04rate\"0\n" +
	"\n" +
	"GetRateReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"d\n" +
	"\vGetRateResp\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"\x1b\n" +
	"\x19GetSupportedCurrenciesReq\"<\n" +
	"\x1aGetSupportedCurrenciesResp\x12\x1e\n" +
	"\n" +
	"currencies\x18\x01 \x03(\tR\n" +
	"currencies2\x93\x01\n" +
	"\x04Rate\x12.\n" +
	"\aGetRate\x12\x10.rate.GetRateReq\x1a\x11.rate.GetRateResp\x12[\n" +
	"\x16GetSupportedCurrencies\x12\x1f.rate.GetSupportedCurrenciesReq\x1a .rate.GetSupportedCurrenciesRespB\bZ\x06./rateb\x06proto3"

var (
	file_desc_rate_proto_rawDescOnce sync.Once
	file_desc_rate_proto_rawDescData []byte
)

func file_desc_rate_proto_rawDescGZIP() []byte {
	file_desc_rate_proto_rawDescOnce.Do(func() {
		file_desc_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_rate_proto_rawDesc), len(file_desc_rate_proto_rawDesc)))
	})
	return file_desc_rate_proto_rawDescData
}

var file_desc_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_desc_rate_proto_goTypes = []any{
	(*GetRateReq)(nil),                 // 0: rate.GetRateReq
	(*GetRateResp)(nil),                // 1: rate.GetRateResp
	(*GetSupportedCurrenciesReq)(nil),  // 2: rate.GetSupportedCurrenciesReq
	(*GetSupportedCurrenciesResp)(nil), // 3: rate.GetSupportedCurrenciesResp
}
var file_desc_rate_proto_depIdxs = []int32{
	0, // 0: rate.Rate.GetRate:input_type -> rate.GetRateReq
	2, // 1: rate.Rate.GetSupportedCurrencies:input_type -> rate.GetSupportedCurrenciesReq
	1, // 2: rate.Rate.GetRate:output_type -> rate.GetRateResp
	3, // 3: rate.Rate.GetSupportedCurrencies:output_type -> rate.GetSupportedCurrenciesResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desc_rate_proto_init() }
func file_desc_rate_proto_init() {
	if File_desc_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_rate_proto_rawDesc), len(file_desc_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_rate_proto_goTypes,
		DependencyIndexes: file_desc_rate_proto_depIdxs,
		MessageInfos:      file_desc_rate_proto_msgTypes,
	}.Build()
	File_desc_rate_proto = out.File
	file_desc_rate_proto_goTypes = nil
	file_desc_rate_proto_depIdxs = nil
}
