// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: favorite.proto

package favoriteclient

import (
	"context"

	"freeexchanged/app/favorite/cmd/rpc/favorite"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingReq  = favorite.PingReq
	PingResp = favorite.PingResp

	Favorite interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	}

	defaultFavorite struct {
		cli zrpc.Client
	}
)

func NewFavorite(cli zrpc.Client) Favorite {
	return &defaultFavorite{
		cli: cli,
	}
}

func (m *defaultFavorite) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
