// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package server

import (
	"context"

	"freeexchanged/app/interaction/cmd/rpc/internal/logic"
	"freeexchanged/app/interaction/cmd/rpc/internal/svc"
	"freeexchanged/app/interaction/cmd/rpc/pb"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) Like(ctx context.Context, in *pb.LikeReq) (*pb.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *InteractionServer) Unlike(ctx context.Context, in *pb.UnlikeReq) (*pb.UnlikeResp, error) {
	l := logic.NewUnlikeLogic(ctx, s.svcCtx)
	return l.Unlike(in)
}

func (s *InteractionServer) Read(ctx context.Context, in *pb.ReadReq) (*pb.ReadResp, error) {
	l := logic.NewReadLogic(ctx, s.svcCtx)
	return l.Read(in)
}
