// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ranking.proto

package server

import (
	"context"

	"freeexchanged/app/ranking/cmd/rpc/internal/logic"
	"freeexchanged/app/ranking/cmd/rpc/internal/svc"
	"freeexchanged/app/ranking/cmd/rpc/pb"
)

type RankingServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRankingServer
}

func NewRankingServer(svcCtx *svc.ServiceContext) *RankingServer {
	return &RankingServer{
		svcCtx: svcCtx,
	}
}

func (s *RankingServer) GetTop(ctx context.Context, in *pb.GetTopReq) (*pb.GetTopResp, error) {
	l := logic.NewGetTopLogic(ctx, s.svcCtx)
	return l.GetTop(in)
}
