// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/article.proto

package article

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Model Definition ---
type ArticleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	LikeCount     int64                  `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount     int64                  `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_desc_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ArticleInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ArticleInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// --- Request/Response ---
type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_desc_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{1}
}

func (x *PublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type PublishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResp) Reset() {
	*x = PublishResp{}
	mi := &file_desc_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResp) ProtoMessage() {}

func (x *PublishResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResp.ProtoReflect.Descriptor instead.
func (*PublishResp) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResp) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type GetArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	mi := &file_desc_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *ArticleInfo           `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResp) Reset() {
	*x = GetArticleResp{}
	mi := &file_desc_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResp) ProtoMessage() {}

func (x *GetArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResp.ProtoReflect.Descriptor instead.
func (*GetArticleResp) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResp) GetArticle() *ArticleInfo {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticlesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"` // 可选，0表示查所有
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesReq) Reset() {
	*x = ListArticlesReq{}
	mi := &file_desc_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesReq) ProtoMessage() {}

func (x *ListArticlesReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesReq.ProtoReflect.Descriptor instead.
func (*ListArticlesReq) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ListArticlesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListArticlesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*ArticleInfo         `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResp) Reset() {
	*x = ListArticlesResp{}
	mi := &file_desc_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResp) ProtoMessage() {}

func (x *ListArticlesResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResp.ProtoReflect.Descriptor instead.
func (*ListArticlesResp) Descriptor() ([]byte, []int) {
	return file_desc_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResp) GetArticles() []*ArticleInfo {
	if x != nil {
		return x.Articles
	}
	return nil
}

var File_desc_article_proto protoreflect.FileDescriptor

const file_desc_article_proto_rawDesc = "" +
	"\n" +
	"\x12desc/article.proto\x12\aarticle\"\x82\x02\n" +
	"\vArticleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\x03R\tviewCount\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\x03R\n" +
	"updateTime\"Y\n" +
	"\n" +
	"PublishReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\",\n" +
	"\vPublishResp\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\"\x1f\n" +
	"\rGetArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x0eGetArticleResp\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.article.ArticleInfoR\aarticle\"_\n" +
	"\x0fListArticlesReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"D\n" +
	"\x10ListArticlesResp\x120\n" +
	"\barticles\x18\x01 \x03(\v2\x14.article.ArticleInfoR\barticles2\xc3\x01\n" +
	"\aArticle\x124\n" +
	"\aPublish\x12\x13.article.PublishReq\x1a\x14.article.PublishResp\x12=\n" +
	"\n" +
	"GetArticle\x12\x16.article.GetArticleReq\x1a\x17.article.GetArticleResp\x12C\n" +
	"\fListArticles\x12\x18.article.ListArticlesReq\x1a\x19.article.ListArticlesRespB\vZ\t./articleb\x06proto3"

var (
	file_desc_article_proto_rawDescOnce sync.Once
	file_desc_article_proto_rawDescData []byte
)

func file_desc_article_proto_rawDescGZIP() []byte {
	file_desc_article_proto_rawDescOnce.Do(func() {
		file_desc_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_article_proto_rawDesc), len(file_desc_article_proto_rawDesc)))
	})
	return file_desc_article_proto_rawDescData
}

var file_desc_article_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_desc_article_proto_goTypes = []any{
	(*ArticleInfo)(nil),      // 0: article.ArticleInfo
	(*PublishReq)(nil),       // 1: article.PublishReq
	(*PublishResp)(nil),      // 2: article.PublishResp
	(*GetArticleReq)(nil),    // 3: article.GetArticleReq
	(*GetArticleResp)(nil),   // 4: article.GetArticleResp
	(*ListArticlesReq)(nil),  // 5: article.ListArticlesReq
	(*ListArticlesResp)(nil), // 6: article.ListArticlesResp
}
var file_desc_article_proto_depIdxs = []int32{
	0, // 0: article.GetArticleResp.article:type_name -> article.ArticleInfo
	0, // 1: article.ListArticlesResp.articles:type_name -> article.ArticleInfo
	1, // 2: article.Article.Publish:input_type -> article.PublishReq
	3, // 3: article.Article.GetArticle:input_type -> article.GetArticleReq
	5, // 4: article.Article.ListArticles:input_type -> article.ListArticlesReq
	2, // 5: article.Article.Publish:output_type -> article.PublishResp
	4, // 6: article.Article.GetArticle:output_type -> article.GetArticleResp
	6, // 7: article.Article.ListArticles:output_type -> article.ListArticlesResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_desc_article_proto_init() }
func file_desc_article_proto_init() {
	if File_desc_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_article_proto_rawDesc), len(file_desc_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_article_proto_goTypes,
		DependencyIndexes: file_desc_article_proto_depIdxs,
		MessageInfos:      file_desc_article_proto_msgTypes,
	}.Build()
	File_desc_article_proto = out.File
	file_desc_article_proto_goTypes = nil
	file_desc_article_proto_depIdxs = nil
}
