// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	watchlistFieldNames          = builder.RawFieldNames(&Watchlist{})
	watchlistRows                = strings.Join(watchlistFieldNames, ",")
	watchlistRowsExpectAutoSet   = strings.Join(stringx.Remove(watchlistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	watchlistRowsWithPlaceHolder = strings.Join(stringx.Remove(watchlistFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	watchlistModel interface {
		Insert(ctx context.Context, data *Watchlist) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Watchlist, error)
		FindOneByUserIdCurrencyPair(ctx context.Context, userId int64, currencyPair string) (*Watchlist, error)
		Update(ctx context.Context, data *Watchlist) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWatchlistModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Watchlist struct {
		Id           int64     `db:"id"`
		UserId       int64     `db:"user_id"`       // ç”¨æˆ·ID
		CurrencyPair string    `db:"currency_pair"` // è´§å¸å¯¹
		CreateTime   time.Time `db:"create_time"`
	}
)

func newWatchlistModel(conn sqlx.SqlConn) *defaultWatchlistModel {
	return &defaultWatchlistModel{
		conn:  conn,
		table: "`watchlist`",
	}
}

func (m *defaultWatchlistModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWatchlistModel) FindOne(ctx context.Context, id int64) (*Watchlist, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", watchlistRows, m.table)
	var resp Watchlist
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWatchlistModel) FindOneByUserIdCurrencyPair(ctx context.Context, userId int64, currencyPair string) (*Watchlist, error) {
	var resp Watchlist
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `currency_pair` = ? limit 1", watchlistRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, currencyPair)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWatchlistModel) Insert(ctx context.Context, data *Watchlist) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, watchlistRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CurrencyPair)
	return ret, err
}

func (m *defaultWatchlistModel) Update(ctx context.Context, newData *Watchlist) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, watchlistRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.CurrencyPair, newData.Id)
	return err
}

func (m *defaultWatchlistModel) tableName() string {
	return m.table
}
