// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/interaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_desc_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *LikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeReq) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type LikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResp) Reset() {
	*x = LikeResp{}
	mi := &file_desc_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResp) ProtoMessage() {}

func (x *LikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResp.ProtoReflect.Descriptor instead.
func (*LikeResp) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{1}
}

type UnlikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReq) Reset() {
	*x = UnlikeReq{}
	mi := &file_desc_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReq) ProtoMessage() {}

func (x *UnlikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReq.ProtoReflect.Descriptor instead.
func (*UnlikeReq) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeReq) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type UnlikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeResp) Reset() {
	*x = UnlikeResp{}
	mi := &file_desc_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeResp) ProtoMessage() {}

func (x *UnlikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeResp.ProtoReflect.Descriptor instead.
func (*UnlikeResp) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{3}
}

type ReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     int64                  `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReq) Reset() {
	*x = ReadReq{}
	mi := &file_desc_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReq) ProtoMessage() {}

func (x *ReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReq.ProtoReflect.Descriptor instead.
func (*ReadReq) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *ReadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadReq) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResp) Reset() {
	*x = ReadResp{}
	mi := &file_desc_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResp) ProtoMessage() {}

func (x *ReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResp.ProtoReflect.Descriptor instead.
func (*ReadResp) Descriptor() ([]byte, []int) {
	return file_desc_interaction_proto_rawDescGZIP(), []int{5}
}

var File_desc_interaction_proto protoreflect.FileDescriptor

const file_desc_interaction_proto_rawDesc = "" +
	"\n" +
	"\x16desc/interaction.proto\x12\vinteraction\"A\n" +
	"\aLikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\"\n" +
	"\n" +
	"\bLikeResp\"C\n" +
	"\tUnlikeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\"\f\n" +
	"\n" +
	"UnlikeResp\"A\n" +
	"\aReadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\"\n" +
	"\n" +
	"\bReadResp2\xb2\x01\n" +
	"\vInteraction\x123\n" +
	"\x04Like\x12\x14.interaction.LikeReq\x1a\x15.interaction.LikeResp\x129\n" +
	"\x06Unlike\x12\x16.interaction.UnlikeReq\x1a\x17.interaction.UnlikeResp\x123\n" +
	"\x04Read\x12\x14.interaction.ReadReq\x1a\x15.interaction.ReadRespB\x06Z\x04./pbb\x06proto3"

var (
	file_desc_interaction_proto_rawDescOnce sync.Once
	file_desc_interaction_proto_rawDescData []byte
)

func file_desc_interaction_proto_rawDescGZIP() []byte {
	file_desc_interaction_proto_rawDescOnce.Do(func() {
		file_desc_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_interaction_proto_rawDesc), len(file_desc_interaction_proto_rawDesc)))
	})
	return file_desc_interaction_proto_rawDescData
}

var file_desc_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_desc_interaction_proto_goTypes = []any{
	(*LikeReq)(nil),    // 0: interaction.LikeReq
	(*LikeResp)(nil),   // 1: interaction.LikeResp
	(*UnlikeReq)(nil),  // 2: interaction.UnlikeReq
	(*UnlikeResp)(nil), // 3: interaction.UnlikeResp
	(*ReadReq)(nil),    // 4: interaction.ReadReq
	(*ReadResp)(nil),   // 5: interaction.ReadResp
}
var file_desc_interaction_proto_depIdxs = []int32{
	0, // 0: interaction.Interaction.Like:input_type -> interaction.LikeReq
	2, // 1: interaction.Interaction.Unlike:input_type -> interaction.UnlikeReq
	4, // 2: interaction.Interaction.Read:input_type -> interaction.ReadReq
	1, // 3: interaction.Interaction.Like:output_type -> interaction.LikeResp
	3, // 4: interaction.Interaction.Unlike:output_type -> interaction.UnlikeResp
	5, // 5: interaction.Interaction.Read:output_type -> interaction.ReadResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desc_interaction_proto_init() }
func file_desc_interaction_proto_init() {
	if File_desc_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_interaction_proto_rawDesc), len(file_desc_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_interaction_proto_goTypes,
		DependencyIndexes: file_desc_interaction_proto_depIdxs,
		MessageInfos:      file_desc_interaction_proto_msgTypes,
	}.Build()
	File_desc_interaction_proto = out.File
	file_desc_interaction_proto_goTypes = nil
	file_desc_interaction_proto_depIdxs = nil
}
