// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interaction.proto

package interaction

import (
	"context"

	"freeexchanged/app/interaction/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LikeReq    = pb.LikeReq
	LikeResp   = pb.LikeResp
	ReadReq    = pb.ReadReq
	ReadResp   = pb.ReadResp
	UnlikeReq  = pb.UnlikeReq
	UnlikeResp = pb.UnlikeResp

	Interaction interface {
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
		Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error)
		Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

func (m *defaultInteraction) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

func (m *defaultInteraction) Unlike(ctx context.Context, in *UnlikeReq, opts ...grpc.CallOption) (*UnlikeResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.Unlike(ctx, in, opts...)
}

func (m *defaultInteraction) Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.Read(ctx, in, opts...)
}
