apiVersion: v1
kind: ConfigMap
metadata:
  name: ranking-stream-config
  namespace: freeexchanged
data:
  stream.yaml: |
    BizRedis:
      Host: redis-svc:6379
      Type: node

    Prometheus:
      Host: 0.0.0.0
      Port: 9098
      Path: /metrics

    Kafka:
      Brokers:
        - kafka-svc:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-stream
  namespace: freeexchanged
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: ranking-stream
  template:
    metadata:
      labels:
        app: ranking-stream
    spec:
      containers:
      - name: ranking-stream
        image: freeexchanged/ranking-stream:v0.1.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: freeexchanged-secrets
        ports:
        - name: metrics
          containerPort: 9098
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /app/etc
      volumes:
      - name: config
        configMap:
          name: ranking-stream-config
---
apiVersion: v1
kind: Service
metadata:
  name: ranking-stream-svc
  namespace: freeexchanged
spec:
  selector:
    app: ranking-stream
  ports:
  - name: metrics
    port: 9098
    targetPort: 9098
