apiVersion: v1
kind: Secret
metadata:
  name: freeexchanged-secrets
  namespace: freeexchanged
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "freeexchanged"
  MYSQL_DSN: "root:root@tcp(mysql-svc:3306)/freeexchanged?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
  PASETO_ACCESS_SECRET: "yNgBwFodlqorfsT21cTjdafFVhU3lXUKBq9OBNW8IHU="
  GRAFANA_ADMIN_PASSWORD: "admin"
