// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: watchlist.proto

package server

import (
	"context"

	"freeexchanged/app/watchlist/cmd/rpc/internal/logic"
	"freeexchanged/app/watchlist/cmd/rpc/internal/svc"
	"freeexchanged/app/watchlist/cmd/rpc/watchlist"
)

type WatchlistServer struct {
	svcCtx *svc.ServiceContext
	watchlist.UnimplementedWatchlistServer
}

func NewWatchlistServer(svcCtx *svc.ServiceContext) *WatchlistServer {
	return &WatchlistServer{
		svcCtx: svcCtx,
	}
}

func (s *WatchlistServer) AddWatch(ctx context.Context, in *watchlist.AddWatchReq) (*watchlist.AddWatchResp, error) {
	l := logic.NewAddWatchLogic(ctx, s.svcCtx)
	return l.AddWatch(in)
}

func (s *WatchlistServer) RemoveWatch(ctx context.Context, in *watchlist.RemoveWatchReq) (*watchlist.RemoveWatchResp, error) {
	l := logic.NewRemoveWatchLogic(ctx, s.svcCtx)
	return l.RemoveWatch(in)
}

func (s *WatchlistServer) GetWatchlist(ctx context.Context, in *watchlist.GetWatchlistReq) (*watchlist.GetWatchlistResp, error) {
	l := logic.NewGetWatchlistLogic(ctx, s.svcCtx)
	return l.GetWatchlist(in)
}
