// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	article "freeexchanged/app/gateway/internal/handler/article"
	interaction "freeexchanged/app/gateway/internal/handler/interaction"
	ranking "freeexchanged/app/gateway/internal/handler/ranking"
	rate "freeexchanged/app/gateway/internal/handler/rate"
	user "freeexchanged/app/gateway/internal/handler/user"
	watchlist "freeexchanged/app/gateway/internal/handler/watchlist"
	"freeexchanged/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PasetoMiddleware},
			[]rest.Route{
				{
					// Publish new article
					Method:  http.MethodPost,
					Path:    "/publish",
					Handler: article.PublishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/article"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PasetoMiddleware, serverCtx.RateLimitMiddleware},
			[]rest.Route{
				{
					// 点赞/取消点赞
					Method:  http.MethodPost,
					Path:    "/like",
					Handler: interaction.LikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取热榜
				Method:  http.MethodGet,
				Path:    "/top",
				Handler: ranking.GetTopHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/ranking"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取汇率（公开接口，无需鉴权）
				Method:  http.MethodGet,
				Path:    "/",
				Handler: rate.GetRateHandler(serverCtx),
			},
			{
				// 获取支持的货币列表
				Method:  http.MethodGet,
				Path:    "/currencies",
				Handler: rate.GetCurrenciesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/rate"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PasetoMiddleware},
			[]rest.Route{
				{
					// 获取用户信息 (需要鉴权)
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					// 用户注销 (需要鉴权)
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					// 健康检查 (需要鉴权)
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: user.PingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PasetoMiddleware},
			[]rest.Route{
				{
					// Add currency pair to watchlist
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: watchlist.AddWatchHandler(serverCtx),
				},
				{
					// Get watchlist with real-time rates
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: watchlist.GetWatchlistHandler(serverCtx),
				},
				{
					// Remove currency pair from watchlist
					Method:  http.MethodPost,
					Path:    "/remove",
					Handler: watchlist.RemoveWatchHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/watchlist"),
	)
}
