// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rate.proto

package server

import (
	"context"

	"freeexchanged/app/rate/cmd/rpc/internal/logic"
	"freeexchanged/app/rate/cmd/rpc/internal/svc"
	"freeexchanged/app/rate/cmd/rpc/rate"
)

type RateServer struct {
	svcCtx *svc.ServiceContext
	rate.UnimplementedRateServer
}

func NewRateServer(svcCtx *svc.ServiceContext) *RateServer {
	return &RateServer{
		svcCtx: svcCtx,
	}
}

func (s *RateServer) GetRate(ctx context.Context, in *rate.GetRateReq) (*rate.GetRateResp, error) {
	l := logic.NewGetRateLogic(ctx, s.svcCtx)
	return l.GetRate(in)
}

func (s *RateServer) GetSupportedCurrencies(ctx context.Context, in *rate.GetSupportedCurrenciesReq) (*rate.GetSupportedCurrenciesResp, error) {
	l := logic.NewGetSupportedCurrenciesLogic(ctx, s.svcCtx)
	return l.GetSupportedCurrencies(in)
}
