// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rate.proto

package rateClient

import (
	"context"

	"freeexchanged/app/rate/cmd/rpc/rate"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetRateReq                 = rate.GetRateReq
	GetRateResp                = rate.GetRateResp
	GetSupportedCurrenciesReq  = rate.GetSupportedCurrenciesReq
	GetSupportedCurrenciesResp = rate.GetSupportedCurrenciesResp

	Rate interface {
		GetRate(ctx context.Context, in *GetRateReq, opts ...grpc.CallOption) (*GetRateResp, error)
		GetSupportedCurrencies(ctx context.Context, in *GetSupportedCurrenciesReq, opts ...grpc.CallOption) (*GetSupportedCurrenciesResp, error)
	}

	defaultRate struct {
		cli zrpc.Client
	}
)

func NewRate(cli zrpc.Client) Rate {
	return &defaultRate{
		cli: cli,
	}
}

func (m *defaultRate) GetRate(ctx context.Context, in *GetRateReq, opts ...grpc.CallOption) (*GetRateResp, error) {
	client := rate.NewRateClient(m.cli.Conn())
	return client.GetRate(ctx, in, opts...)
}

func (m *defaultRate) GetSupportedCurrencies(ctx context.Context, in *GetSupportedCurrenciesReq, opts ...grpc.CallOption) (*GetSupportedCurrenciesResp, error) {
	client := rate.NewRateClient(m.cli.Conn())
	return client.GetSupportedCurrencies(ctx, in, opts...)
}
