// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/favorite.proto

package favorite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_desc_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_desc_favorite_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_desc_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_desc_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_desc_favorite_proto protoreflect.FileDescriptor

const file_desc_favorite_proto_rawDesc = "" +
	"\n" +
	"\x13desc/favorite.proto\x12\bfavorite\"\t\n" +
	"\aPingReq\"$\n" +
	"\bPingResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage29\n" +
	"\bFavorite\x12-\n" +
	"\x04Ping\x12\x11.favorite.PingReq\x1a\x12.favorite.PingRespB\fZ\n" +
	"./favoriteb\x06proto3"

var (
	file_desc_favorite_proto_rawDescOnce sync.Once
	file_desc_favorite_proto_rawDescData []byte
)

func file_desc_favorite_proto_rawDescGZIP() []byte {
	file_desc_favorite_proto_rawDescOnce.Do(func() {
		file_desc_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_favorite_proto_rawDesc), len(file_desc_favorite_proto_rawDesc)))
	})
	return file_desc_favorite_proto_rawDescData
}

var file_desc_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_desc_favorite_proto_goTypes = []any{
	(*PingReq)(nil),  // 0: favorite.PingReq
	(*PingResp)(nil), // 1: favorite.PingResp
}
var file_desc_favorite_proto_depIdxs = []int32{
	0, // 0: favorite.Favorite.Ping:input_type -> favorite.PingReq
	1, // 1: favorite.Favorite.Ping:output_type -> favorite.PingResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desc_favorite_proto_init() }
func file_desc_favorite_proto_init() {
	if File_desc_favorite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_favorite_proto_rawDesc), len(file_desc_favorite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_favorite_proto_goTypes,
		DependencyIndexes: file_desc_favorite_proto_depIdxs,
		MessageInfos:      file_desc_favorite_proto_msgTypes,
	}.Build()
	File_desc_favorite_proto = out.File
	file_desc_favorite_proto_goTypes = nil
	file_desc_favorite_proto_depIdxs = nil
}
