// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: article.proto

package server

import (
	"context"

	"freeexchanged/app/article/cmd/rpc/article"
	"freeexchanged/app/article/cmd/rpc/internal/logic"
	"freeexchanged/app/article/cmd/rpc/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	article.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *article.PublishReq) (*article.PublishResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) GetArticle(ctx context.Context, in *article.GetArticleReq) (*article.GetArticleResp, error) {
	l := logic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServer) ListArticles(ctx context.Context, in *article.ListArticlesReq) (*article.ListArticlesResp, error) {
	l := logic.NewListArticlesLogic(ctx, s.svcCtx)
	return l.ListArticles(in)
}
