// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: watchlist.proto

package watchlistClient

import (
	"context"

	"freeexchanged/app/watchlist/cmd/rpc/watchlist"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddWatchReq      = watchlist.AddWatchReq
	AddWatchResp     = watchlist.AddWatchResp
	GetWatchlistReq  = watchlist.GetWatchlistReq
	GetWatchlistResp = watchlist.GetWatchlistResp
	RemoveWatchReq   = watchlist.RemoveWatchReq
	RemoveWatchResp  = watchlist.RemoveWatchResp
	WatchItem        = watchlist.WatchItem

	Watchlist interface {
		AddWatch(ctx context.Context, in *AddWatchReq, opts ...grpc.CallOption) (*AddWatchResp, error)
		RemoveWatch(ctx context.Context, in *RemoveWatchReq, opts ...grpc.CallOption) (*RemoveWatchResp, error)
		GetWatchlist(ctx context.Context, in *GetWatchlistReq, opts ...grpc.CallOption) (*GetWatchlistResp, error)
	}

	defaultWatchlist struct {
		cli zrpc.Client
	}
)

func NewWatchlist(cli zrpc.Client) Watchlist {
	return &defaultWatchlist{
		cli: cli,
	}
}

func (m *defaultWatchlist) AddWatch(ctx context.Context, in *AddWatchReq, opts ...grpc.CallOption) (*AddWatchResp, error) {
	client := watchlist.NewWatchlistClient(m.cli.Conn())
	return client.AddWatch(ctx, in, opts...)
}

func (m *defaultWatchlist) RemoveWatch(ctx context.Context, in *RemoveWatchReq, opts ...grpc.CallOption) (*RemoveWatchResp, error) {
	client := watchlist.NewWatchlistClient(m.cli.Conn())
	return client.RemoveWatch(ctx, in, opts...)
}

func (m *defaultWatchlist) GetWatchlist(ctx context.Context, in *GetWatchlistReq, opts ...grpc.CallOption) (*GetWatchlistResp, error) {
	client := watchlist.NewWatchlistClient(m.cli.Conn())
	return client.GetWatchlist(ctx, in, opts...)
}
