// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: desc/watchlist.proto

package watchlist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Watchlist_AddWatch_FullMethodName     = "/watchlist.Watchlist/AddWatch"
	Watchlist_RemoveWatch_FullMethodName  = "/watchlist.Watchlist/RemoveWatch"
	Watchlist_GetWatchlist_FullMethodName = "/watchlist.Watchlist/GetWatchlist"
)

// WatchlistClient is the client API for Watchlist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchlistClient interface {
	AddWatch(ctx context.Context, in *AddWatchReq, opts ...grpc.CallOption) (*AddWatchResp, error)
	RemoveWatch(ctx context.Context, in *RemoveWatchReq, opts ...grpc.CallOption) (*RemoveWatchResp, error)
	GetWatchlist(ctx context.Context, in *GetWatchlistReq, opts ...grpc.CallOption) (*GetWatchlistResp, error)
}

type watchlistClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchlistClient(cc grpc.ClientConnInterface) WatchlistClient {
	return &watchlistClient{cc}
}

func (c *watchlistClient) AddWatch(ctx context.Context, in *AddWatchReq, opts ...grpc.CallOption) (*AddWatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWatchResp)
	err := c.cc.Invoke(ctx, Watchlist_AddWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistClient) RemoveWatch(ctx context.Context, in *RemoveWatchReq, opts ...grpc.CallOption) (*RemoveWatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWatchResp)
	err := c.cc.Invoke(ctx, Watchlist_RemoveWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistClient) GetWatchlist(ctx context.Context, in *GetWatchlistReq, opts ...grpc.CallOption) (*GetWatchlistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatchlistResp)
	err := c.cc.Invoke(ctx, Watchlist_GetWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchlistServer is the server API for Watchlist service.
// All implementations must embed UnimplementedWatchlistServer
// for forward compatibility.
type WatchlistServer interface {
	AddWatch(context.Context, *AddWatchReq) (*AddWatchResp, error)
	RemoveWatch(context.Context, *RemoveWatchReq) (*RemoveWatchResp, error)
	GetWatchlist(context.Context, *GetWatchlistReq) (*GetWatchlistResp, error)
	mustEmbedUnimplementedWatchlistServer()
}

// UnimplementedWatchlistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchlistServer struct{}

func (UnimplementedWatchlistServer) AddWatch(context.Context, *AddWatchReq) (*AddWatchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWatch not implemented")
}
func (UnimplementedWatchlistServer) RemoveWatch(context.Context, *RemoveWatchReq) (*RemoveWatchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWatch not implemented")
}
func (UnimplementedWatchlistServer) GetWatchlist(context.Context, *GetWatchlistReq) (*GetWatchlistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchlist not implemented")
}
func (UnimplementedWatchlistServer) mustEmbedUnimplementedWatchlistServer() {}
func (UnimplementedWatchlistServer) testEmbeddedByValue()                   {}

// UnsafeWatchlistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchlistServer will
// result in compilation errors.
type UnsafeWatchlistServer interface {
	mustEmbedUnimplementedWatchlistServer()
}

func RegisterWatchlistServer(s grpc.ServiceRegistrar, srv WatchlistServer) {
	// If the following call panics, it indicates UnimplementedWatchlistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Watchlist_ServiceDesc, srv)
}

func _Watchlist_AddWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServer).AddWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchlist_AddWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServer).AddWatch(ctx, req.(*AddWatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watchlist_RemoveWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServer).RemoveWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchlist_RemoveWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServer).RemoveWatch(ctx, req.(*RemoveWatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watchlist_GetWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchlistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServer).GetWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Watchlist_GetWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServer).GetWatchlist(ctx, req.(*GetWatchlistReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Watchlist_ServiceDesc is the grpc.ServiceDesc for Watchlist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watchlist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchlist.Watchlist",
	HandlerType: (*WatchlistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWatch",
			Handler:    _Watchlist_AddWatch_Handler,
		},
		{
			MethodName: "RemoveWatch",
			Handler:    _Watchlist_RemoveWatch_Handler,
		},
		{
			MethodName: "GetWatchlist",
			Handler:    _Watchlist_GetWatchlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc/watchlist.proto",
}
