// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/watchlist.proto

package watchlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyPair  string                 `protobuf:"bytes,1,opt,name=currency_pair,json=currencyPair,proto3" json:"currency_pair,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItem) Reset() {
	*x = WatchItem{}
	mi := &file_desc_watchlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItem) ProtoMessage() {}

func (x *WatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItem.ProtoReflect.Descriptor instead.
func (*WatchItem) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{0}
}

func (x *WatchItem) GetCurrencyPair() string {
	if x != nil {
		return x.CurrencyPair
	}
	return ""
}

func (x *WatchItem) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *WatchItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddWatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyPair  string                 `protobuf:"bytes,2,opt,name=currency_pair,json=currencyPair,proto3" json:"currency_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWatchReq) Reset() {
	*x = AddWatchReq{}
	mi := &file_desc_watchlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchReq) ProtoMessage() {}

func (x *AddWatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchReq.ProtoReflect.Descriptor instead.
func (*AddWatchReq) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{1}
}

func (x *AddWatchReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddWatchReq) GetCurrencyPair() string {
	if x != nil {
		return x.CurrencyPair
	}
	return ""
}

type AddWatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWatchResp) Reset() {
	*x = AddWatchResp{}
	mi := &file_desc_watchlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchResp) ProtoMessage() {}

func (x *AddWatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchResp.ProtoReflect.Descriptor instead.
func (*AddWatchResp) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{2}
}

type RemoveWatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyPair  string                 `protobuf:"bytes,2,opt,name=currency_pair,json=currencyPair,proto3" json:"currency_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWatchReq) Reset() {
	*x = RemoveWatchReq{}
	mi := &file_desc_watchlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchReq) ProtoMessage() {}

func (x *RemoveWatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchReq.ProtoReflect.Descriptor instead.
func (*RemoveWatchReq) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveWatchReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveWatchReq) GetCurrencyPair() string {
	if x != nil {
		return x.CurrencyPair
	}
	return ""
}

type RemoveWatchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWatchResp) Reset() {
	*x = RemoveWatchResp{}
	mi := &file_desc_watchlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchResp) ProtoMessage() {}

func (x *RemoveWatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchResp.ProtoReflect.Descriptor instead.
func (*RemoveWatchResp) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{4}
}

type GetWatchlistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchlistReq) Reset() {
	*x = GetWatchlistReq{}
	mi := &file_desc_watchlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchlistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistReq) ProtoMessage() {}

func (x *GetWatchlistReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistReq.ProtoReflect.Descriptor instead.
func (*GetWatchlistReq) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{5}
}

func (x *GetWatchlistReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetWatchlistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WatchItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchlistResp) Reset() {
	*x = GetWatchlistResp{}
	mi := &file_desc_watchlist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchlistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistResp) ProtoMessage() {}

func (x *GetWatchlistResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_watchlist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistResp.ProtoReflect.Descriptor instead.
func (*GetWatchlistResp) Descriptor() ([]byte, []int) {
	return file_desc_watchlist_proto_rawDescGZIP(), []int{6}
}

func (x *GetWatchlistResp) GetItems() []*WatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_desc_watchlist_proto protoreflect.FileDescriptor

const file_desc_watchlist_proto_rawDesc = "" +
	"\n" +
	"\x14desc/watchlist.proto\x12\twatchlist\"c\n" +
	"\tWatchItem\x12#\n" +
	"\rcurrency_pair\x18\x01 \x01(\tR\fcurrencyPair\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"K\n" +
	"\vAddWatchReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rcurrency_pair\x18\x02 \x01(\tR\fcurrencyPair\"\x0e\n" +
	"\fAddWatchResp\"N\n" +
	"\x0eRemoveWatchReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rcurrency_pair\x18\x02 \x01(\tR\fcurrencyPair\"\x11\n" +
	"\x0fRemoveWatchResp\"*\n" +
	"\x0fGetWatchlistReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\">\n" +
	"\x10GetWatchlistResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.watchlist.WatchItemR\x05items2\xd7\x01\n" +
	"\tWatchlist\x12;\n" +
	"\bAddWatch\x12\x16.watchlist.AddWatchReq\x1a\x17.watchlist.AddWatchResp\x12D\n" +
	"\vRemoveWatch\x12\x19.watchlist.RemoveWatchReq\x1a\x1a.watchlist.RemoveWatchResp\x12G\n" +
	"\fGetWatchlist\x12\x1a.watchlist.GetWatchlistReq\x1a\x1b.watchlist.GetWatchlistRespB\rZ\v./watchlistb\x06proto3"

var (
	file_desc_watchlist_proto_rawDescOnce sync.Once
	file_desc_watchlist_proto_rawDescData []byte
)

func file_desc_watchlist_proto_rawDescGZIP() []byte {
	file_desc_watchlist_proto_rawDescOnce.Do(func() {
		file_desc_watchlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_watchlist_proto_rawDesc), len(file_desc_watchlist_proto_rawDesc)))
	})
	return file_desc_watchlist_proto_rawDescData
}

var file_desc_watchlist_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_desc_watchlist_proto_goTypes = []any{
	(*WatchItem)(nil),        // 0: watchlist.WatchItem
	(*AddWatchReq)(nil),      // 1: watchlist.AddWatchReq
	(*AddWatchResp)(nil),     // 2: watchlist.AddWatchResp
	(*RemoveWatchReq)(nil),   // 3: watchlist.RemoveWatchReq
	(*RemoveWatchResp)(nil),  // 4: watchlist.RemoveWatchResp
	(*GetWatchlistReq)(nil),  // 5: watchlist.GetWatchlistReq
	(*GetWatchlistResp)(nil), // 6: watchlist.GetWatchlistResp
}
var file_desc_watchlist_proto_depIdxs = []int32{
	0, // 0: watchlist.GetWatchlistResp.items:type_name -> watchlist.WatchItem
	1, // 1: watchlist.Watchlist.AddWatch:input_type -> watchlist.AddWatchReq
	3, // 2: watchlist.Watchlist.RemoveWatch:input_type -> watchlist.RemoveWatchReq
	5, // 3: watchlist.Watchlist.GetWatchlist:input_type -> watchlist.GetWatchlistReq
	2, // 4: watchlist.Watchlist.AddWatch:output_type -> watchlist.AddWatchResp
	4, // 5: watchlist.Watchlist.RemoveWatch:output_type -> watchlist.RemoveWatchResp
	6, // 6: watchlist.Watchlist.GetWatchlist:output_type -> watchlist.GetWatchlistResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_desc_watchlist_proto_init() }
func file_desc_watchlist_proto_init() {
	if File_desc_watchlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_watchlist_proto_rawDesc), len(file_desc_watchlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_watchlist_proto_goTypes,
		DependencyIndexes: file_desc_watchlist_proto_depIdxs,
		MessageInfos:      file_desc_watchlist_proto_msgTypes,
	}.Build()
	File_desc_watchlist_proto = out.File
	file_desc_watchlist_proto_goTypes = nil
	file_desc_watchlist_proto_depIdxs = nil
}
