// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: desc/ranking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int64                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // 额外返回标题，方便前端展示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_desc_ranking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_desc_ranking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_desc_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *RankItem) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetTopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"` // Top N，如 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopReq) Reset() {
	*x = GetTopReq{}
	mi := &file_desc_ranking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopReq) ProtoMessage() {}

func (x *GetTopReq) ProtoReflect() protoreflect.Message {
	mi := &file_desc_ranking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopReq.ProtoReflect.Descriptor instead.
func (*GetTopReq) Descriptor() ([]byte, []int) {
	return file_desc_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopReq) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type GetTopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RankItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopResp) Reset() {
	*x = GetTopResp{}
	mi := &file_desc_ranking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopResp) ProtoMessage() {}

func (x *GetTopResp) ProtoReflect() protoreflect.Message {
	mi := &file_desc_ranking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopResp.ProtoReflect.Descriptor instead.
func (*GetTopResp) Descriptor() ([]byte, []int) {
	return file_desc_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopResp) GetItems() []*RankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_desc_ranking_proto protoreflect.FileDescriptor

const file_desc_ranking_proto_rawDesc = "" +
	"\n" +
	"\x12desc/ranking.proto\x12\aranking\"U\n" +
	"\bRankItem\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"\x19\n" +
	"\tGetTopReq\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"5\n" +
	"\n" +
	"GetTopResp\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.ranking.RankItemR\x05items2<\n" +
	"\aRanking\x121\n" +
	"\x06GetTop\x12\x12.ranking.GetTopReq\x1a\x13.ranking.GetTopRespB\x06Z\x04./pbb\x06proto3"

var (
	file_desc_ranking_proto_rawDescOnce sync.Once
	file_desc_ranking_proto_rawDescData []byte
)

func file_desc_ranking_proto_rawDescGZIP() []byte {
	file_desc_ranking_proto_rawDescOnce.Do(func() {
		file_desc_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desc_ranking_proto_rawDesc), len(file_desc_ranking_proto_rawDesc)))
	})
	return file_desc_ranking_proto_rawDescData
}

var file_desc_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_desc_ranking_proto_goTypes = []any{
	(*RankItem)(nil),   // 0: ranking.RankItem
	(*GetTopReq)(nil),  // 1: ranking.GetTopReq
	(*GetTopResp)(nil), // 2: ranking.GetTopResp
}
var file_desc_ranking_proto_depIdxs = []int32{
	0, // 0: ranking.GetTopResp.items:type_name -> ranking.RankItem
	1, // 1: ranking.Ranking.GetTop:input_type -> ranking.GetTopReq
	2, // 2: ranking.Ranking.GetTop:output_type -> ranking.GetTopResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_desc_ranking_proto_init() }
func file_desc_ranking_proto_init() {
	if File_desc_ranking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desc_ranking_proto_rawDesc), len(file_desc_ranking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desc_ranking_proto_goTypes,
		DependencyIndexes: file_desc_ranking_proto_depIdxs,
		MessageInfos:      file_desc_ranking_proto_msgTypes,
	}.Build()
	File_desc_ranking_proto = out.File
	file_desc_ranking_proto_goTypes = nil
	file_desc_ranking_proto_depIdxs = nil
}
