server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /free {
        return 308 /free/;
    }

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /free/assets/ {
        rewrite ^/free/(.*)$ /$1 break;
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /free/ {
        rewrite ^/free/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
