// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddWatchReq struct {
	CurrencyPair string `json:"currency_pair"`
}

type AddWatchResp struct {
}

type GetCurrenciesReq struct {
}

type GetCurrenciesResp struct {
	Currencies []string `json:"currencies"`
}

type GetRateReq struct {
	From string `form:"from"`
	To   string `form:"to"`
}

type GetRateResp struct {
	From      string  `json:"from"`
	To        string  `json:"to"`
	Rate      float64 `json:"rate"`
	UpdatedAt int64   `json:"updated_at"`
}

type GetTopReq struct {
	N int32 `form:"n,default=10"`
}

type GetTopResp struct {
	Items []RankItem `json:"items"`
}

type GetWatchlistResp struct {
	Items []WatchItem `json:"items"`
}

type LikeReq struct {
	ArticleId int64 `json:"article_id"`
	Action    int   `json:"action,optional"` // 1:点赞 2:取消点赞 (默认1)
}

type LikeResp struct {
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expire_at"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type PingReq struct {
}

type PingResp struct {
	Msg string `json:"msg"`
}

type PublishArticleReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PublishArticleResp struct {
	ArticleId int64 `json:"article_id"`
}

type RankItem struct {
	ArticleId int64  `json:"article_id"`
	Score     int64  `json:"score"`
	Title     string `json:"title"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expire_at"`
}

type RemoveWatchReq struct {
	CurrencyPair string `json:"currency_pair"`
}

type RemoveWatchResp struct {
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type WatchItem struct {
	CurrencyPair string  `json:"currency_pair"`
	Rate         float64 `json:"rate"`
	UpdatedAt    int64   `json:"updated_at"`
}
